### ISSUE TITLE
Background and link text hard to read

### ISSUE THREAD

**Issue by degoeym** [columbusrb/columbusrb.com#10]
Hit the page just now to see what was planned for the next meeting and noticed the layout has been updated a bit.

Any text set as a link is very hard to read. Mousing over the text makes it legible, but simply trying to read links on the page is difficult.

**Comment by alexmoore** [comment]
I don't think this issue exists anymore, the CSS / colors have changed since this issue was opened.

Old site:  https://web.archive.org/web/20150925180013/http://www.columbusrb.com/

**Comment by alexmoore** [comment]
@belongstorachel ^^

**Comment by belongstorachel** [comment]
👍

**Comment by degoeym** [comment]
Ah, yep, been so long I forgot this was hanging out there.
