### ISSUE TITLE
Oauth for logging in is broken

### ISSUE THREAD

**Issue by belongstorachel** [columbusrb/columbusrb.com#117]
As an admin, I'm no longer able to log into the site
repro steps:

go to http://columbusrb.com/admin_users/sign_in
Click the login link
Page shows as "The page you were looking for doesn't exist"

**Comment by belongstorachel** [comment]
```
Started GET "/admin_users/auth/google_oauth2" for 98.31.55.28 at 2022-09-02 03:34:16 +0000
AbstractController::ActionNotFound (The action 'passthru' could not be found for Admin::SessionsController):
```

**Comment by szechyjs** [comment]
The button/link issue has been fixed, however we have a `redirect_uri` mismatch issue. I'm guessing this is related to switching to https.

```
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

If you're the app developer, register the redirect URI in the Google Cloud Console.
Request details: redirect_uri=https://columbusrb.com/admin_users/auth/google_oauth2/callback
```

@belongstorachel @joncanady any idea who can update this on the Google side?
