### ISSUE TITLE
Add info for the Board of Directors

### ISSUE THREAD

**Issue by belongstorachel** [columbusrb/columbusrb.com#12]
Add a page or section for the current and historical members of the board of directors. This page can be static or dynamic 

Board of Directors

2017
TBA on 1/16/2017
Biographies can be pulled from http://candidate.columbusrb.com/ once the members are announced.

2016
Matt Darby - President
Benjamin Winkler - Secretary
Tracy Rood - Treasurer
Jon Canady
Rachel Slaby

2015 (I'm not sure who held President/Treasurer/Secretary, will probably just need to ask)
Jon Canady
Brian Crosby
Matt Darby
Tracy Rood
Benjamin Winkler

**Comment by alexmoore** [comment]
2017 Board:

Rachel Slaby - President
Tracy Rood - Treasurer
Clara Kridler - Secretary
Matt Darby - Statler Muppet
Jon Canady - Waldorf Muppet

**Comment by mdarby** [comment]
LGTM

**Comment by mdarby** [comment]
2015 the CRB Board did not exist so it was just kinda, me.

**Comment by belongstorachel** [comment]
Nick Collins and I are going to do this one :)
