### ISSUE TITLE
Add a fundraiser page

### ISSUE THREAD

**Issue by belongstorachel** [columbusrb/columbusrb.com#14]
There's not a lot of things we pay for, but there are a few: ie the domains (columbusrb.com and .org), the meetup group (https://www.meetup.com/pricing/), and who knows what else Matt Darby pays for out of pocket. We don't charge a membership fee to join, so instead we'd like to have a way to raise funds. We'd like to be able to have a "can we get enough orders" basic form (Kickstarter-ish?).

As a real example: We want to sell Drink glasses for $10 each as a fundraiser. 

<img width="166" alt="screen shot 2017-01-15 at 2 49 23 pm" src="https://cloud.githubusercontent.com/assets/20931/21965629/e691aa92-db31-11e6-9b04-ae5e8e6a9265.png"> 
The minimum we need to order is 72 glasses. The more we order, the better the margin is for the fundraiser. 

The information we want to collect is: 

Name / Email address
How many Drink Glasses?

As an Administrator, we'd like to be able to see the list of email addresses and a total number of glasses we need to order.

**Comment by carolinecodes** [comment]
I'll work on this.

**Comment by belongstorachel** [comment]
Hi @carolinecodes, I'm going to close this issue since it's no longer as important as other issues that are currently open. If you do want to contribute please feel free to reopen this issue. 

Thanks!
