### ISSUE TITLE
Add a Contributing.md file

### ISSUE THREAD

**Issue by belongstorachel** [columbusrb/columbusrb.com#15]
We'd like for people to be encouraged to contribute, especially early career or people new to programming. Because of that, we'd like to have a clear set of guidelines for contributing. (This will also show up as a banner when someone creates a new issue in GitHub). 

Here's an example: https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md

One of the things we'd like to specify is that we prefer junior developers or new developers to be the one to create the PR's, and senior developers be the one to review the PRs. However, it's ok if seniors pair with juniors.

**Comment by matthewbussa** [comment]
Picked up

**Comment by matthewbussa** [comment]
Added a Pull Request #26

**Comment by belongstorachel** [comment]
👍
