### ISSUE TITLE
Add section about the non-profit status and board members

### ISSUE THREAD

**Issue by croz1007** [columbusrb/columbusrb.com#19]
It would be great to have the information about the CRB Non-profit status along with details about how that works. Maybe even the details of how the board works (bylaws and such).

Along with that, I think we need to have the details of the board members (bio, twitter, github, etc.) so people know who they can directly reach out to with questions.

**Comment by belongstorachel** [comment]
Relates to https://github.com/columbusrb/columbusrb.com/issues/12

**Comment by mdarby** [comment]
Definitely a great idea and long overdue :)

**Comment by belongstorachel** [comment]
I'm going to close this one in favor of #12
