### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by thodson2010** [columbusrb/columbusrb.com#41]
Not able to investigate issue thoroughly right now, but it appears columbusrb.com is down. 

columbusrb.com didn’t send any data.
ERR_EMPTY_RESPONSE

I will see if I can investigate this issue tonight.

**Comment by belongstorachel** [comment]
This appears to be an issue with Heroku

https://status.heroku.com/incidents/1334

"Free apps in the US will not currently be able to restart following idling. We are working on resolving this remaining issue."

We use the free app, and the website can not start up

**Comment by belongstorachel** [comment]
@thodson2010 the site has started back up. Thanks for reporting the issue. I'm going to close it now. :)
