### ISSUE TITLE
Make the company name link to their website

### ISSUE THREAD

**Issue by mikegee** [columbusrb/columbusrb.com#49]
Instead of putting their URL next to the name of the company without anything clickable.

![screen shot 2018-03-16 at 1 19 22 pm](https://user-images.githubusercontent.com/14068/37534966-ab5924b6-291c-11e8-9ce2-0d9b9f578b1b.png)

^ this part of the website

**Comment by kamal2311** [comment]
Working on it. Kamal and Dan from pair columbus.

**Comment by belongstorachel** [comment]
This is live now. Thank you Kamal and Dan!
